const translations = {
    ru: {
        appName: "Какаха",
        week: "Неделя",
        month: "Месяц",
        year: "Год",
        tags: "Теги",
        color: "Цвет",
        shape: "Форма",
        bristol: "Бристоль",
        count: "Количество",
        volume: "Объем",
        support: "Сказать спасибо",
        mailTo: "Написать нам",
        privacy: "Политика конфиденциальности",
        reset: "Сбросить данные",
        create: "Создать",
        cancel: "Отменить",
        remove: "Удалить",
        update: "Обновить",
        when: "Когда",
        add: "Добавить",
        change: "Изменить",
        newTag: "Новый тег",
        previousPeriod: "Предыдущий период",
        nextPeriod: "Следующий период",
        mainNavigation: "Основная навигация",
        calendar: "Календарь",
        record: "Запись",
        stats: "Статистика",
        person: "Профиль",
        back: "Назад",
        selectDate: "Выбрать дату",
        selectTime: "Выбрать время",
        bristolScale: "Форма по Бристольской шкале",
        addTag: "Добавить тег",
        previous: "Ранее",
        next: "Далее",
        volumeRange: "Объем от 1 до 5",

        g: 'гр',
        kg: 'кг',
        y: 'г',
        noRecords: 'Нет данных за период',
        tagActions: 'нажмите на тег, чтобы его удалить или редактировать',

        birthdate: 'Дата рождения',
        sex: 'Пол',
        female: 'Женщина',
        male: 'Мужчина',
        weight: 'Вес',
        age: 'Возраст',

        yes: 'Да',
        no: 'Нет',

        removeQuestion: 'Удалить запись?',
        resetQuestion: 'Удалить все записи?',

        withFails: 'Ничего не вышло',

        defaultTags: [
            'Боль',
            'Газы',
            'Вздутие',
            'Напряжение',
            'Кофе',
            'Лекарства',
            'Прогулка',
            'Бег',
            'Стресс',
            'Еда'
        ],
        colors: {
            white: 'Белая',
            gray: 'Серая',
            yellow: 'Желтая',
            orange: 'Оранжевая',
            'light-brown': 'Светло-коричневая',
            brown: 'Коричневая',
            'dark-brown': 'Темно-коричневая',
            black: 'Черная',
            green: 'Зеленая',
            red: 'Красная'
        },
        volumes: ['Очень мало', 'Мало', 'Средне', 'Много', 'Очень много'],

        bristols: [
            'Ничего не вышло',
            '1 — отдельные твердые комочки',
            '2 — колбаска с комочками',
            '3 — колбаска с трещинами',
            '4 — гладкая, мягкая, оформленная',
            '5 — мягкие комочки с четкими краями',
            '6 — мягкие рыхлые кусочки',
            '7 — водянистая, без твердых частей'
        ],
        brs: [
            'Ничего',
            'Твердая',
            'Комковатая',
            'Потрескавшаяся',
            'Гладкая',
            'Мягкая',
            'Рыхлая',
            'Водянистая',
        ],
        mons: ['янв', 'фев', 'мар', 'апр', 'май', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
        months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
        wds: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
        ms: ['Я', 'Ф', 'М', 'А', 'М', 'И', 'И', 'А', 'С', 'О', 'Н', 'Д']
    },
    en: {
        appName: "Kakaha",
        week: "Week",
        month: "Month",
        year: "Year",
        tags: "Tags",
        color: "Color",
        shape: "Shape",
        bristol: "Bristol",
        count: "Count",
        volume: "Volume",
        support: "Say thanks",
        mailTo: "Contact us",
        privacy: "Privacy Policy",
        reset: "Reset data",
        create: "Create",
        cancel: "Cancel",
        remove: "Remove",
        update: "Update",
        when: "When",
        add: "Add",
        change: "Change",
        newTag: "New tag",
        previousPeriod: "Previous period",
        nextPeriod: "Next period",
        mainNavigation: "Main navigation",
        calendar: "Calendar",
        record: "Record",
        stats: "Statistics",
        person: "Profile",
        back: "Back",
        selectDate: "Select date",
        selectTime: "Select time",
        bristolScale: "Bristol stool form scale",
        addTag: "Add tag",
        previousMonth: "Previous month",
        nextMonth: "Next month",
        volumeRange: "Volume from 1 to 5",

        g: 'g',
        kg: 'kg',
        y: 'y',
        noRecords: 'No data for the period',
        tagActions: 'Click on the tag to delete or edit it',

        birthdate: 'Birth Date',
        sex: 'Sex',
        f: 'F',
        m: 'M',
        female: 'Female',
        male: 'Male',
        weight: 'Weight',
        age: 'Age',

        removeQuestion: 'Remove record?',
        resetQuestion: 'Remove all records?',
        yes: 'Yes',
        no: 'No',

        withFails: 'Nothing came of me',

        defaultTags: [
            'Pain',
            'Gas',
            'Bloating',
            'Tension',
            'Coffee',
            'Medications',
            'Walk',
            'Running',
            'Stress',
            'Eating'
        ],
        colors: {
            white: 'White',
            gray: 'Gray',
            yellow: 'Yellow',
            orange: 'Orange',
            'light-brown': 'Light brown',
            brown: 'Brown',
            'dark-brown': 'Dark brown',
            black: 'Black',
            green: 'Green',
            red: 'Red'
        },
        volumes: ['Very few', 'Few', 'Average', 'Many', 'Very many'],
        bristols: [
            "Nothing came of me",
            '1 — individual hard lumps',
            '2 — sausage with lumps',
            '3 — sausage with cracks',
            '4 — smooth, soft, decorated',
            '5 — soft lumps with clear edges',
            '6 — soft, loose pieces',
            '7 — watery, without solid parts'
        ],
        brs: [
            'Nothing',
            'Solid',
            'Lumpy',
            'Cracked',
            'Smooth',
            'Soft',
            'Loose',
            'Watery',
        ],
        mons: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
        months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        wds: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        ms: ['I', 'F', 'M', 'A', 'M', 'I', 'I', 'A', 'C', 'O', 'N', 'D']
    }
}
